learning_rates:
  - 0.0003
gamma: 0.99
gae_lambda: 0.95
clip: 0.2
ent_coef: 0.0
critic_factor: 0.5
max_grad_norm: 0.5
n_updates: 10
#n_episodes: 5 # n_batch
#max_iter: 252
max_timesteps: 2048
batch_size: 64